spring: 
  datasource : 
    url : jdbc:mysql://localhost:3306/transportador
    username : root
    password : 1234
    driver-class-name : com.mysql.jdbc.Driver

  jpa :
    hibernate :
      dialect : org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
