#config database
spring: 
    datasource : 
        url : jdbc:mysql://localhost:3306/fornecedor
        username : root
        password : 1234
        driver-class-name : com.mysql.jdbc.Driver

    jpa :
       properties : 
        hibernate :
            dialect : org.hibernate.dialect.MySQL5Dialect
            ddl-auto: create
