spring: 
  datasource : 
    url : jdbc:mysql://localhost:3306/fornecedor
    username : root
    password : 1234
    
  jpa :
    hibernate :
      dialect : org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update 
